#We import the webdriver from selenium...
from selenium import webdriver
#We are using the statement "import time" to give implicit or explict wait...
import time
#We are import the usage of keyboard & mouse...
from selenium.webdriver.common.keys import Keys
print("Test case started")
#Open google chrome browser...
driver = webdriver.Chrome(executable_path='../Selenium_Python/Driver/chromedriver.exe')
#Maximize the window size...
driver.maximize_window()
#Delete all cookies...
driver.delete_all_cookies()
#Navigate to the url...
driver.get("https://www.gmail.com")
#Identify the user name text box and enter the value...
driver.find_element_by_id("identifierId").send_keys("frogy366@gmail.com")
#We can add a wait...
time.sleep(2)
#Click on the next button...
driver.find_element_by_xpath("//*[@id='identifierNext']/div/button/div[2]").click()
time.sleep(3)
#Identify the password text box and enter a value...
driver.find_element_by_name("password").send_keys("*********")
time.sleep(3)
#Click on the next botton...
driver.find_element_by_xpath("//*[@id='passwordNext']/div/button/div[2]").click()
time.sleep(3)
#Close the browser
driver.close()
print("Gmail login has been successfully completed")

